apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rbdxitest
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.1.210:6789
  pool: k8stest
  adminId: kube
  adminSecretNamespace: default
  adminSecretName: ceph-secret-rbd
  userId: kube
  userSecretName: ceph-secret-rbd